version: 0.2

phases:
  install:
    commands:
      - gem install cfn-nag
      - cfn_nag_rules
      - aws s3 cp s3://$S3_BUCKET_NAME/build/update_params.py build/update_params.py
  build:
    commands:
      - aws cloudformation validate-template --template-body file://$(pwd)/template.yml
      - cfn_nag_scan --input-path ./template.yml
      - pip install boto3 && python build/update_params.py
artifacts:
  files: '**/*'